apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:    
  name: triggercmd-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: triggercmd-admin
subjects:
- kind: ServiceAccount
  name: triggercmd-admin
  namespace: kube-system